import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className='dark:bg-[#00113B] bg-[#fff]'>
        {children}
        </div>
        </body>
    </html>
  )
}
